"""tabelas iniciais de auth

Revision ID: 2fb3782a38ee
Revises: 
Create Date: 2026-06-04 10:07:09.010669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb3782a38ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('professor', 'secretaria', 'diretora', name='tipofuncionario'), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('token_reset_senha', sa.String(length=100), nullable=True),
    sa.Column('token_reset_senha_exp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_funcionarios_token_reset_senha'), ['token_reset_senha'], unique=True)
        batch_op.create_index(batch_op.f('ix_funcionarios_usuario'), ['usuario'], unique=True)

    op.create_table('responsaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('email_confirmado', sa.Boolean(), nullable=False),
    sa.Column('token_confirmacao', sa.String(length=100), nullable=True),
    sa.Column('token_confirmacao_exp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_reset_senha', sa.String(length=100), nullable=True),
    sa.Column('token_reset_senha_exp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responsaveis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responsaveis_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_responsaveis_token_confirmacao'), ['token_confirmacao'], unique=True)
        batch_op.create_index(batch_op.f('ix_responsaveis_token_reset_senha'), ['token_reset_senha'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsaveis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responsaveis_token_reset_senha'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_token_confirmacao'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_email'))

    op.drop_table('responsaveis')
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_usuario'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_token_reset_senha'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_email'))

    op.drop_table('funcionarios')
    # ### end Alembic commands ###
