"""turmas e alunos

Revision ID: c6c8c35c1674
Revises: 2fb3782a38ee
Create Date: 2026-06-04 12:19:14.062087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c8c35c1674'
down_revision = '2fb3782a38ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=50), nullable=False),
    sa.Column('turma', sa.String(length=5), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['funcionarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turmas_professor_id'), ['professor_id'], unique=False)

    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_alunos_responsavel_id'), ['responsavel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_turma_id'), ['turma_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_turma_id'))
        batch_op.drop_index(batch_op.f('ix_alunos_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_alunos_matricula'))

    op.drop_table('alunos')
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_professor_id'))

    op.drop_table('turmas')
    # ### end Alembic commands ###
