"""responsavel email pendente e troca

Revision ID: da20469620fd
Revises: c6c8c35c1674
Create Date: 2026-06-04 12:37:57.486888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da20469620fd'
down_revision = 'c6c8c35c1674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsaveis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_pendente', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_troca_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('token_troca_email_exp', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_responsaveis_token_troca_email'), ['token_troca_email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsaveis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responsaveis_token_troca_email'))
        batch_op.drop_column('token_troca_email_exp')
        batch_op.drop_column('token_troca_email')
        batch_op.drop_column('email_pendente')

    # ### end Alembic commands ###
